version: "3.9"

services:
  php:
    image: php:7.4-apache
    container_name: php
    build:
      context: Docker/php # folder path to docker file
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/project
    depends_on:
      - mysql
      - elasticsearch
    networks:
      - web_net

  mysql:
    image: mariadb:10.4.0
    container_name: mysql
    restart: always
    build:
      context: Docker/mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    volumes:
      # you should keep this for keeping database after restarting docker
      - ./Docker/mysql/databases:/var/lib/mysql
    networks:
      - web_net

  elasticsearch:
    container_name: elastic
    image: elasticsearch:7.17.10
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    #volumes:
    #  - Docker/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      #- 9300:9300
      - 9200:9200
    networks:
      - web_net

  phpmyadmin:
    container_name: phpmyadmin
    restart: always
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - PMA_HOST=mysql #mysql container name
      - PMA_USER=root
      - PMA_PASSWORD=root
      - UPLOAD_LIMIT=800M
      - MAX_EXECUTION_TIME=80000000
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - web_net

  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8585:8080
      - 50000:50000
    container_name: jenkins
    volumes:
#      - /home/${myname}/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  composer:
    restart: 'no'
    image: library/composer:latest
    command: install
    volumes:
      - .:/app

networks:
  web_net:
    driver: bridge
